// <auto-generated />
namespace TRbooks.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddCustomersBirthDateProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCustomersBirthDateProp));
        
        string IMigrationMetadata.Id
        {
            get { return "202005251911412_AddCustomersBirthDateProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
